server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jesus-medina13/Mingeso-PEP3-2023-1
          search-paths: config-data
  application:
    name: config